#!/bin/bash
. $(dirname $0)/libhell

echo "git-hell $version"
echo
echo Dependencies:
git --version
sed --version | head -1
tempfile --version
mkdir --version | head -1
dirname --version | head -1

exit 0

