#!/bin/bash
# VERSION: 1
# HELP: Show git-hell information
# USAGE: info
. $(dirname $0)/libhell

echo "git-hell $version"
echo
echo Dependencies:
git --version
sed --version | head -1
tempfile --version

# coreutils
mkdir --version | head -1
basename --version | head -1
dirname --version | head -1
cut --version | head -1

exit 0

