#!/bin/bash
# VERSION: 1
# HELP: Add public key to account
# USAGE: addkey
. $(dirname $0)/libhell

user=$1

# Read in the SSH key
echo -n "Enter key: "
read key

# write key to file
keyfile=$(tempfile) && echo "$key" >"$keyfile" 2>/dev/null || die 'cannot create temporary file.'

# check fingerprint
if ! ssh-keygen -lf "$keyfile" &>/dev/null; then
	rm "$keyfile"
	die 'invalid key entered.'
fi

rm "$keyfile"
append_key "$user" "$key" || die 'cannot add key to the account.'
echo 'Key successfuly added.'

exit 0

