#!/bin/bash
# VERSION: 1
# HELP: Add public key to account
# USAGE: addkey
. $(dirname $0)/libhell

user=$1

# Read in the SSH key
echo -n "Enter key: "
read key

# write key to file
keyfile=$(tempfile) && echo "$key" >$keyfile

# check fingerprint
if ! ssh-keygen -lf $keyfile &>/dev/null; then
	rm $keyfile
	bye "Invalid key entered."
fi

rm $keyfile
store_key "$user" "$key"
echo 'Key successfuly added.'

exit 0

