#!/bin/bash
# VERSION: 1
# HELP: Enables account
# USAGE: enable
. $(dirname $0)/libhell

user=$1

# if already enabled
account_read $user
$account_active && bye "Account '$user' already enabled."

# enable account: write entry to accounts file
account_change "$account_user" "$account_pass" true
echo "Account '$user' enabled."

exit 0

