#!/bin/bash
# VERSION: 1
# HELP: Show short help
# USAGE: help [command]
. $(dirname $0)/libhell


show_all() {
	print_header
	echo 
	echo "Available commands:"
	cd $(dirname $0)
	for f in cmd_*; do
		if [ -x "$f" ]; then
			local cmd=${f:4}
			printf "  %-10s" $cmd
			echo $(read_tag $cmd HELP)
		fi
	done
}


show_one() {
	local cmd=$1
	print_header
	echo
	echo "Command: $cmd"
	echo -e "  version:\t" $(read_tag "$cmd" VERSION)
	echo -e "  usage:\t" $(read_tag "$cmd" USAGE)
	echo -e "  help:\t\t$(read_tag "$cmd" HELP)"
}


[ -z "$2" ] && show_all || show_one $2

exit 0

