#!/bin/bash
. $(dirname $0)/libhell


shift			# get rid of -c, no check!
set $*
if [ "$1" == "auth" ]; then
	auth_key=true
	user=$2
	shift 2
	command="$SSH_ORIGINAL_COMMAND"
else
	auth_key=false
	user=$1
	shift
	command="$@"
fi

check_credentials

[ -z "$command" ] && err 'missing command.'
[ "${command:0:3}" = "git" ] && run_git "$user" $command

set $command
execfile="$execdir/cmd_$1"
test -x "$execfile" || err "Invalid command '$1'."
shift	# ignore command name $1
$execfile $user $*

exit 0
			
#export VAR_CLEAN=”`echo “${SSH_ORIGINAL_COMMAND}” | tr -cd ‘[:alnum:] [:space:]’`”
