#!/bin/bash
. $(dirname $0)/libhell


shift			# get rid of -c, no check!
set $*
if [ "$1" == "auth" ]; then
	auth_key=true
	account_user=$2
	shift 2
	set $SSH_ORIGINAL_COMMAND
else
	auth_key=false
fi

# ask for password if no public key
$auth_key || request_userpass

# important to check this (security hole: ssh user@host auth jure ...)
[ -z "$1" ] && die 'missing command.'

# if public key and git command
$auth_key && is_git $1 && run_git "$account_user" $*

# otherwise it is git-hell command
execfile="$(command_path $1)"
test -x "$execfile" || die "Invalid command '$1'."
shift	# ignore command name $1
$execfile $account_user $*

exit 0

