#!/bin/bash
. $(dirname $0)/libhell


shift			# get rid of -c, no check!
set $*
if [ "$1" == "auth" ]; then
	auth_key=true
	user=$2
	shift 2
	set $SSH_ORIGINAL_COMMAND
else
	auth_key=false
fi

# ask for password if no public key
$auth_key || request_userpass

# important to check this (security hole: ssh user@host auth jure ...)
[ -z "$1" ] && err 'missing command.'

# if public key and git command
$auth_key && is_git $1 && run_git "$user" $*

# otherwise it is git-hell command
execfile="$execdir/cmd_$1"
test -x "$execfile" || err "Invalid command '$1'."
shift	# ignore command name $1
$execfile $user $*

exit 0

